### ISSUE TITLE
Error: Cannot find module './../script'

### ISSUE THREAD

**Issue by hanandika** [tohenk/node-sms-terminal#1]
here the log
```
Gitas-MacBook-Pro:node-sms-terminal hanandika$ node app.js 
Reading configuration /Users/hanandika/Desktop/Project/node-sms-terminal/config.json
Available ports: tty.Bluetooth-Incoming-Port
Available drivers:
- Generic
- Sony Ericsson
- Huawei
- EC1260-2
- ZTE
- Siemens C55
- Huawei E173
- Huawei E3372
- QUALCOMM
- WAVECOM


Error: Cannot find module './../script'
```

and did manualy download zip from [https://github.com/tohenk/node-ntjs](https://github.com/tohenk/node-ntjs)
extract to 'ui/lib/script/' folder

now working perfectly ...
not yet test with actual device/driver

**Comment by tohenk** [comment]
This repository is part of https://github.com/tohenk/node-sms-gw. For installation and configuration refers to https://github.com/tohenk/node-sms-gw/blob/master/README.md.
