### ISSUE TITLE
OSX Catalina - SerialPort.list no longer takes a callback 

### ISSUE THREAD

**Issue by pacmac** [tohenk/node-sms-terminal#3]
Hopefully this is self-explanatory :-)

```
node app.js --auto
Reading configuration /Users/xxx/nodejs/sms/config.json
(node:11837) UnhandledPromiseRejectionWarning: TypeError: SerialPort.list no longer takes a callback and only returns a promise
```

**Comment by pacmac** [comment]
I had to install latest version of serialport as the version 7.1.5 in the package.json will not install at all on catalina !

**Comment by pacmac** [comment]
OK, have installed on debian now, it is running and I can see the dashboard.

But when I run it using --auto it just hangs at:

```
node app.js --auto
Reading configuration /usr/share/nodejs/node-sms-gw/terminal/config.json
Available ports: ttyUSB0, ttyUSB1, ttyUSB2, ttyUSB3, ttyUSB4, ttyS0, ttyS1, ttyS2, ttyS3
Available drivers:
- Generic
- Sony Ericsson
- Huawei
- EC1260-2
- ZTE
- Siemens C55
- Huawei E173
- Huawei E3372
- QUALCOMM
- WAVECOM


Application ready on port 8000...
ttyUSB0: Try detecting modem...
ttyUSB0: not an AT modem.
ttyUSB1: Try detecting modem...
ttyUSB1: not an AT modem.
ttyUSB2: Try detecting modem...
```

I am using SIMCOM SIM7000C - what new commands would I need to add to the drivers file for this to be recognized ?

**Comment by tohenk** [comment]
Can you attach the log files located at `logs` folder named `ttyUSB2.log`?

**Comment by pacmac** [comment]
I have made progress and confirmed that the modem is connected on ttyUSB2, I can communicate with it using linux screen command.

But when I open the control panel and select "Tasks > Send AT Command" there are no terminals listed ?

**Comment by pacmac** [comment]
```
27-01 19:40:40.688 TX> AT
27-01 19:40:40.692 RX> AT

OK
27-01 19:40:40.693 TX> ATI
27-01 19:40:40.695 RX> ATI
27-01 19:40:40.695 RX> SIM7000C R1351

OK
27-01 19:43:56.054 TX> AT
27-01 19:43:56.059 RX> AT

OK
27-01 19:43:56.060 TX> ATI
27-01 19:43:56.064 RX> ATI
27-01 19:43:56.064 RX> SIM7000C R1351

OK
27-01 20:33:54.628 TX> AT
27-01 20:33:54.638 RX> AT

OK
27-01 20:33:54.639 TX> ATI
27-01 20:33:54.643 RX> ATI

SIM7000C R1351

OK
27-01 20:36:54.168 TX> AT
27-01 20:36:54.172 RX> AT

OK
27-01 20:36:54.173 TX> ATI
27-01 20:36:54.178 RX> ATI

SIM7000C R1351

OK
```

**Comment by tohenk** [comment]
Try 88a85830de610a1bd179d0a289959508757ac37b.

**Comment by pacmac** [comment]
Great that worked, now the only error I get is :

`Error: Input/output error setting custom baud rate of 115200`

No doubt that can be fixed :-)

**Comment by tohenk** [comment]
Change or remove `baudRate` (https://github.com/tohenk/node-sms-terminal/blob/master/term.js#L92)

**Comment by diginfo** [comment]
Thanks, I have the gateway and the terminal server running now, but maybe I misunderstand the usage ??

can I use a socket to connect to the gateway to list, read and send messages ?? - I dont see anything in the readme documents ??

**Comment by tohenk** [comment]
See
https://github.com/tohenk/node-sms-gateway/blob/master/term.js#L195
https://github.com/tohenk/node-appserver/blob/master/app/ntmsg.js#L118
